### PR TITLE
Add control to choose between wc_width() and wc_width_cjk()

### PR DESCRIPTION
**Pull request by SlySven**
### Brief overview of PR changes/additions
The previous state of this (novload/development) branch always use `wc_width_cjk()` which is not appropriate for (generally speaking) non East Asian MUDs (*probably*) - this PR adds a persistent, per profile user settable option to control whether to use that CJK specific code or the more general one - the difference **should be** the width used to draw those glyphs which Unicode.org characterises as being ambiguous.

#### Motivation for adding to Mudlet
The current proposal on the main https://github.com/Mudlet/Mudlet/pull/1632 uses the wrong (wide) width for a number of glyphs even within the Latin1 range of codepoints because it uses the `wc_width_cjk()` function in situations (Western Europe MUDs) where the `wc_width()` (narrow width) one should be used for those glyphs.

#### Other info (issues closed, discussion etc)
The existing code uses ranges of characters from Unicode 5.0 from around 10 years ago - those should be re-examined to see whether they need to be expanded to cover any codepoints added since then, given that the standard is now at version 10.0 and more codepoints have been added in the intervening period.

### CODE REVIEW

**Comment by SlySven** [comment]
The `development` (unfortunately the only) branch here needs to have a `git pull origin/main` {or something *like* that} run on it to bring it up to date. This will remove many of the changes leading up to the last two in this PR which are the **two** that I am *actually* proposing.

**Comment by SlySven** [comment]
:+1: OK, that merge has reduced the changes down a lot!

I'm just about to push up a further commit to this PR to make the control have a tri-stated *default* setting that makes the setting depend on the MUD server encoding.

I do want to examine the ranges of characters that Markus used in the `wc_width.c` source to see what updates need to be make for any additions between Unicode 5.0 and the current 10.0 but that can be done separately once this has gone into your `development` branch and the PR that it makes to the main one goes in there.

🔖 In the meantime please add your copyright line to the headers in the files you have modified - this confirms your code to be GPL2 (or at a subsequent user's option a later version) licenced - which is something that we need from contributors (but sometimes forget to remind them).  Actually you need to include the full GPL header (see the files in the `./template` sub-directory) in both `wcwidth.c` and `wcwidth.h` put it above Markus's but leave his in place below it.  His licencing terms look as though we can apply the GPL2+ to the aggregratre of his work and your changes.

\<aside>*You ought to have created a new branch and made your changes to *that* and kept the 'development' one tracking the main repository's one IMHO as it make it hard for you to work on more than one item at a time.*\</aside>

**Comment by novload** [comment]
It seems that I have chosen the wrong merge option and only "Merge pull request #1 from SlySven/fix-cjk-fullwidth-display" is shown in the commits.

I'm not quite sure how to merge SlySven:fix-cjk-fullwidth-display to novload:fix-cjk-fullwidth-display and keep each commit.

I don't quite use git and github.
My English is very poor, I used the translator to write this, I do not know whether it is correct.
I am sorry.

**Comment by SlySven** [comment]
I think you confusion has come about because you have worked on your **development** branch when you should have created a new branch as *a copy of it* which you should have worked on *instead*.

You did the right thing 🎉  when you merged this **P**ull **R**equest into your *development* branch **in this particular case** because it was the *development* branch that you had suggested as the PR to the *main* Mudlet repository.

**However something has gone wrong and it is not showing up [*here*](https://github.com/Mudlet/Mudlet/pull/1632) - I am not certain but I think that you have tried to undo (*revert*) the change and GitHub has spotted that and deliberately ignored these changes.**

With your agreement I will try to copy *everything* you have done and recreate a new PR with the same changes on my repository - with **one** exception - I will *add* the line:

    *   Copyright (C) 2018 by ?????? ?????? novload@outlook.com    *

to the top of each file that you have changed - but I need to know: what is your name to go in the ?????? ?????? space above? :grin:

**Pull request merged**
